var dir_68267d1309a1af8e8297ef4c3efbcdba =
[
    [ "direction.cpp", "direction_8cpp.html", "direction_8cpp" ],
    [ "direction.h", "direction_8h.html", "direction_8h" ],
    [ "gaussian.cpp", "gaussian_8cpp.html", "gaussian_8cpp" ],
    [ "gaussian.h", "gaussian_8h.html", "gaussian_8h" ],
    [ "gaussian.ipp", "gaussian_8ipp.html", "gaussian_8ipp" ],
    [ "gen_test_image.cpp", "gen__test__image_8cpp.html", "gen__test__image_8cpp" ],
    [ "image_io.cpp", "image__io_8cpp.html", "image__io_8cpp" ],
    [ "image_io.h", "image__io_8h.html", "image__io_8h" ],
    [ "magnitude.cpp", "magnitude_8cpp.html", "magnitude_8cpp" ],
    [ "magnitude.h", "magnitude_8h.html", "magnitude_8h" ],
    [ "main.cpp", "main_8cpp.html", "main_8cpp" ],
    [ "main_rvv.cpp", "main__rvv_8cpp.html", "main__rvv_8cpp" ],
    [ "nms_threshold.cpp", "nms__threshold_8cpp.html", "nms__threshold_8cpp" ],
    [ "nms_threshold.h", "nms__threshold_8h.html", "nms__threshold_8h" ],
    [ "rvv_add_test.cpp", "rvv__add__test_8cpp.html", "rvv__add__test_8cpp" ],
    [ "rvv_gaussian.cpp", "rvv__gaussian_8cpp.html", "rvv__gaussian_8cpp" ],
    [ "rvv_gaussian.h", "rvv__gaussian_8h.html", "rvv__gaussian_8h" ],
    [ "rvv_magnitude.cpp", "rvv__magnitude_8cpp.html", "rvv__magnitude_8cpp" ],
    [ "rvv_magnitude.h", "rvv__magnitude_8h.html", "rvv__magnitude_8h" ],
    [ "sobel.cpp", "sobel_8cpp.html", "sobel_8cpp" ],
    [ "sobel.h", "sobel_8h.html", "sobel_8h" ],
    [ "summary.cpp", "summary_8cpp.html", "summary_8cpp" ],
    [ "syscalls.cpp", "syscalls_8cpp.html", "syscalls_8cpp" ]
];